# Generated by Django 4.1.3 on 2022-12-21 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_biodata_remove_user_group_delete_group_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biodata',
            options={'verbose_name_plural': 'Biodata'},
        ),
    ]
